# Generated by Django 5.1.1 on 2024-09-16 07:28

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unknown Course', max_length=100)),
                ('code', models.CharField(default='UNKNOWN', max_length=10, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='honors_minors',
        ),
        migrations.RemoveField(
            model_name='student',
            name='labs_batches',
        ),
        migrations.RemoveField(
            model_name='student',
            name='name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='password',
        ),
        migrations.RemoveField(
            model_name='student',
            name='username',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='honors_minors',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='name',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='password',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='username',
        ),
        migrations.AddField(
            model_name='student',
            name='cgpa',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='student',
            name='roll_number',
            field=models.CharField(blank=True, default=None, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='student',
            name='year_of_study',
            field=models.CharField(default='2024', max_length=4),
        ),
        migrations.AddField(
            model_name='teacher',
            name='faculty_id',
            field=models.CharField(default='UNKNOWN', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(default='Unknown Department', max_length=100),
        ),
        migrations.AlterField(
            model_name='department',
            name='year',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myapp.year'),
        ),
        migrations.AlterField(
            model_name='evensem',
            name='department',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myapp.department'),
        ),
        migrations.AlterField(
            model_name='evensem',
            name='program',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myapp.program'),
        ),
        migrations.AlterField(
            model_name='honorsminors',
            name='even_sem',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myapp.evensem'),
        ),
        migrations.AlterField(
            model_name='honorsminors',
            name='name',
            field=models.CharField(default='Unknown Honors/Minors', max_length=100),
        ),
        migrations.AlterField(
            model_name='honorsminors',
            name='odd_sem',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myapp.oddsem'),
        ),
        migrations.AlterField(
            model_name='labsbatches',
            name='department',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myapp.department'),
        ),
        migrations.AlterField(
            model_name='labsbatches',
            name='name',
            field=models.CharField(default='Unknown Lab Batch', max_length=100),
        ),
        migrations.AlterField(
            model_name='labsbatches',
            name='program',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myapp.program'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='program',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myapp.program'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='student',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myapp.student'),
        ),
        migrations.AlterField(
            model_name='oddsem',
            name='department',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myapp.department'),
        ),
        migrations.AlterField(
            model_name='oddsem',
            name='program',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myapp.program'),
        ),
        migrations.AlterField(
            model_name='program',
            name='department',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myapp.department'),
        ),
        migrations.AlterField(
            model_name='program',
            name='name',
            field=models.CharField(default='Unknown Program', max_length=100),
        ),
        migrations.AlterField(
            model_name='program',
            name='semester',
            field=models.CharField(default='Unknown Semester', max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.department'),
        ),
        migrations.AlterField(
            model_name='student',
            name='even_sem',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.evensem'),
        ),
        migrations.AlterField(
            model_name='student',
            name='odd_sem',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.oddsem'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='department',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.department'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='program',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.program'),
        ),
        migrations.AlterField(
            model_name='year',
            name='name',
            field=models.CharField(default='Unknown Year', max_length=100),
        ),
        migrations.AddField(
            model_name='teacher',
            name='courses_taught',
            field=models.ManyToManyField(blank=True, to='myapp.course'),
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('principal', 'Principal'), ('hod', 'HOD'), ('teacher', 'Teacher'), ('student', 'Student'), ('staff', 'Staff')], default='student', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, related_name='custom_user_set', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='custom_user_permissions_set', to='auth.permission')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.customuser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.customuser'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='HOD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_number', models.CharField(default='Unknown', max_length=50)),
                ('managing_teachers', models.IntegerField(default=0)),
                ('department', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Principal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_location', models.CharField(default='Unknown Location', max_length=255)),
                ('department', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(default='Unknown Position', max_length=100)),
                ('staff_id', models.CharField(default='UNKNOWN', max_length=10, unique=True)),
                ('assigned_department', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.customuser')),
            ],
        ),
    ]
