# Generated by Django 5.1.1 on 2024-09-23 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='time_slot',
            field=models.CharField(blank=True, choices=[('8-9', '8:00 AM - 9:00 AM'), ('9-10', '9:00 AM - 10:00 AM'), ('10-11', '10:00 AM - 11:00 AM'), ('11:15-12:15', '11:15 AM - 12:15 PM'), ('12:15-1:15', '12:15 PM - 1:15 PM'), ('2-3', '2:00 PM - 3:00 PM'), ('3-4', '3:00 PM - 4:00 PM'), ('4-5', '4:00 PM - 5:00 PM')], max_length=20, null=True, verbose_name='Time Slot'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['date', 'time_slot'], name='myapp_atten_date_e37ae6_idx'),
        ),
        migrations.AddIndex(
            model_name='lecture',
            index=models.Index(fields=['date', 'time_slot'], name='myapp_lectu_date_732299_idx'),
        ),
    ]
