# Generated by Django 5.1.1 on 2024-09-17 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='even_sem',
        ),
        migrations.RemoveField(
            model_name='student',
            name='odd_sem',
        ),
    ]
