# Generated by Django 5.1.1 on 2024-09-17 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_student_even_sem_remove_student_odd_sem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
