# Generated by Django 5.1.1 on 2024-09-18 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_principal_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='principal',
            name='office_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
