# Generated by Django 5.1.1 on 2024-09-23 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_attendance_time_slot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_lab',
            field=models.BooleanField(default=False, verbose_name='Is Lab'),
        ),
    ]
