# Generated by Django 5.1.1 on 2024-09-22 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_year_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='semester',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='semester',
            name='year',
            field=models.CharField(choices=[('FE', 'First Year'), ('SE', 'Second Year'), ('TE', 'Third Year'), ('BE', 'Fourth Year')], max_length=2, verbose_name='Year'),
        ),
        migrations.AlterUniqueTogether(
            name='semester',
            unique_together={('session_year', 'semester_number', 'year')},
        ),
    ]
