# Generated by Django 5.1.1 on 2024-09-18 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_student_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='evensem',
            name='semester_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='oddsem',
            name='semester_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='students', to='myapp.course'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='evensem',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.department'),
        ),
        migrations.AlterField(
            model_name='evensem',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.program'),
        ),
        migrations.AlterField(
            model_name='honorsminors',
            name='even_sem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.evensem'),
        ),
        migrations.AlterField(
            model_name='honorsminors',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='honorsminors',
            name='odd_sem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.oddsem'),
        ),
        migrations.AlterField(
            model_name='oddsem',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.department'),
        ),
        migrations.AlterField(
            model_name='oddsem',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.program'),
        ),
        migrations.CreateModel(
            name='SemesterCGPA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_type', models.CharField(choices=[('Odd', 'Odd'), ('Even', 'Even')], max_length=10)),
                ('semester_number', models.PositiveIntegerField()),
                ('cgpa', models.DecimalField(decimal_places=2, max_digits=4)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.student')),
            ],
        ),
    ]
