# Generated by Django 5.1.1 on 2024-09-18 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_principal_office_location'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='hod',
            name='department',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.department'),
        ),
        migrations.AlterField(
            model_name='hod',
            name='managing_teachers',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='hod',
            name='office_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddConstraint(
            model_name='hod',
            constraint=models.UniqueConstraint(fields=('department',), name='unique_hod_per_department'),
        ),
    ]
