# Generated by Django 5.1.1 on 2024-09-16 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_customuser_groups_alter_customuser_role_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hod',
            options={'permissions': [('can_view_hod', 'Can view HOD details')]},
        ),
        migrations.AlterModelOptions(
            name='principal',
            options={'permissions': [('can_view_principal', 'Can view principal details')]},
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'permissions': [('can_view_staff', 'Can view staff details')]},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'permissions': [('can_view_student', 'Can view student details')]},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'permissions': [('can_view_teacher', 'Can view teacher details')]},
        ),
    ]
