# Generated by Django 5.1.1 on 2024-09-18 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_hod_department_alter_hod_managing_teachers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='principal',
            name='department',
        ),
    ]
