# Generated by Django 5.1.1 on 2024-09-18 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_evensem_semester_number_oddsem_semester_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='program',
        ),
    ]
