# Generated by Django 5.1.1 on 2024-09-30 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_attendance_count_attendance_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='batches',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Batches for Labs'),
        ),
        migrations.CreateModel(
            name='Labs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Course Code')),
                ('name', models.CharField(max_length=100, verbose_name='Course Name')),
                ('index', models.IntegerField(default=0, verbose_name='Index')),
                ('semester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lab_semester_list', to='myapp.semester', verbose_name='Semester')),
            ],
        ),
        migrations.CreateModel(
            name='Batches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_options', models.TextField(default='[]', verbose_name='Batch Options')),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='myapp.labs', verbose_name='Lab')),
            ],
        ),
        migrations.AddField(
            model_name='semester',
            name='labs',
            field=models.ManyToManyField(blank=True, related_name='semester_labs', to='myapp.labs', verbose_name='Labs'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='assigned_labs',
            field=models.ManyToManyField(blank=True, related_name='assigned_labs', to='myapp.labs', verbose_name='Assigned Labs'),
        ),
        migrations.AddIndex(
            model_name='labs',
            index=models.Index(fields=['code'], name='myapp_labs_code_e6319a_idx'),
        ),
        migrations.AddIndex(
            model_name='labs',
            index=models.Index(fields=['name'], name='myapp_labs_name_e9866f_idx'),
        ),
    ]
