# Generated by Django 5.1.1 on 2024-09-28 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_student_batches_labs_batches_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='batches',
            field=models.JSONField(blank=True, null=True, verbose_name='Batches for Labs'),
        ),
    ]
