# Generated by Django 5.1.3 on 2024-11-29 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_student_batches_labs_batches_semester_labs_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_batch', models.TextField(blank=True, null=True, verbose_name='Lab Batch')),
                ('date', models.DateField(verbose_name='Date')),
                ('time_slot', models.CharField(blank=True, choices=[('8-9', '8:00 AM - 9:00 AM'), ('9-10', '9:00 AM - 10:00 AM'), ('10-11', '10:00 AM - 11:00 AM'), ('11:15-12:15', '11:15 AM - 12:15 PM'), ('12:15-1:15', '12:15 PM - 1:15 PM'), ('2-3', '2:00 PM - 3:00 PM'), ('3-4', '3:00 PM - 4:00 PM'), ('4-5', '4:00 PM - 5:00 PM')], max_length=20, null=True, verbose_name='Time Slot')),
                ('present', models.BooleanField(default=False, verbose_name='Present')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_attendances', to='myapp.labs', verbose_name='Lab')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_attendances', to='myapp.student', verbose_name='Student')),
            ],
            options={
                'indexes': [models.Index(fields=['date'], name='myapp_labat_date_d03786_idx'), models.Index(fields=['present'], name='myapp_labat_present_8ff172_idx'), models.Index(fields=['date', 'time_slot'], name='myapp_labat_date_6d08df_idx'), models.Index(fields=['lab_batch'], name='myapp_labat_lab_bat_55207a_idx')],
                'unique_together': {('student', 'lab', 'date', 'lab_batch')},
            },
        ),
    ]
