# Generated by Django 5.1.1 on 2024-09-28 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_student_batches'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='assigned_labs',
            field=models.ManyToManyField(blank=True, null=True, related_name='assigned_labs', to='myapp.labs', verbose_name='Assigned Labs'),
        ),
    ]
