# Generated by Django 5.1.3 on 2024-11-29 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_labattendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='labattendance',
            name='count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Count'),
        ),
    ]
