# Generated by Django 5.1.3 on 2024-11-29 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_labattendance_count'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='labattendance',
            unique_together={('student', 'lab', 'date', 'lab_batch', 'count')},
        ),
    ]
