# Generated by Django 5.1.3 on 2024-12-01 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_labattendance_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='honorsminors',
            options={'verbose_name': 'Honors/Minor', 'verbose_name_plural': 'Honors/Minors'},
        ),
        migrations.AddField(
            model_name='honorsminors',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Course Code'),
        ),
        migrations.AlterField(
            model_name='honorsminors',
            name='semester',
            field=models.IntegerField(blank=True, choices=[(5, 'Semester 5'), (6, 'Semester 6'), (7, 'Semester 7'), (8, 'Semester 8')], null=True, verbose_name='Semester'),
        ),
    ]
