# Generated by Django 5.1.1 on 2024-09-28 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_teacher_assigned_labs'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='labs',
            field=models.ManyToManyField(blank=True, related_name='semester_labs', to='myapp.labs', verbose_name='Labs'),
        ),
    ]
