# Generated by Django 5.1.3 on 2024-12-01 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_honorsminors_options_honorsminors_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='assogned_hms',
            field=models.ManyToManyField(blank=True, related_name='assigned_hms', to='myapp.honorsminors', verbose_name='Assigned Honors/Minors'),
        ),
    ]
