# Generated by Django 5.1.1 on 2024-10-03 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_student_batches_labs_batches_semester_labs_and_more'),
        ('myapp', '0011_alter_student_batches'),
    ]

    operations = [
    ]
