# Generated by Django 5.1.3 on 2024-12-01 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_rename_assogned_hms_teacher_assigned_hms_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HmsAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('present', models.BooleanField(default=False, verbose_name='Present')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('count', models.IntegerField(blank=True, default=0, null=True, verbose_name='Count')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('hms_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hms_attendances', to='myapp.honorsminors', verbose_name='HMS Course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hms_attendances', to='myapp.student', verbose_name='Student')),
            ],
            options={
                'indexes': [models.Index(fields=['date'], name='myapp_hmsat_date_d5f3ce_idx'), models.Index(fields=['present'], name='myapp_hmsat_present_079d2b_idx')],
                'unique_together': {('student', 'date', 'count')},
            },
        ),
    ]
